version: "2"

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  kafka:
    image: bitnami/kafka:latest
    #command: tail -f /dev/null
    volumes:
      - "kafka_data:/bitnami"
    ports:
      - "9094:9094"
    environment:
      - BITNAMI_DEBUG=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true  
      - KAFKA_KRAFT_CLUSTER_ID=9YoavaRpTCOitT3Dm2OQFQ
      # For more details see See https://rmoff.net/2018/08/02/kafka-listeners-explained/
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
volumes:
  kafka_data:
    driver: local
